name: Say Hello

on:
    push:
        branches:
            - main

jobs:
    hello_world:
        runs-on: ubuntu-latest
        steps:
            - name: Echo Hello
              run: |
                  echo "Hello, World!"
